name: Greet Arvind on Push

on:
  push:
    branches:
      - main # You can specify the branch you want to trigger this workflow on

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Greet Arvind
        run: echo "hello Arvind, new code is pushed"
